### ISSUE TITLE
Filtering should be more strict

### ISSUE THREAD

**Issue by jachin** [DripEmail/much-select-elm#98]
Right now we are showing a bunch of partial matches.

We're doing this:
![image](https://user-images.githubusercontent.com/42679/151620480-b78a1cfb-9faa-4fe6-a478-06865f73f28d.png)

Maybe we should just be showing this:
![image (1)](https://user-images.githubusercontent.com/42679/151620554-7a5f717a-4527-457e-89b6-95e94264b474.png)

Perhaps we could configure this with an attribute.

**Comment by wokejacqueline** [comment]
i totally agree with this from a design perspective! highlighting is less useful when its noisy, and highlighting the complete word seems like the expected default? here's a nice example of the default behavior from a third-party search provider: 

- https://react-instantsearch.netlify.app/storybook/?path=/story/highlight--default

**Comment by jachin** [comment]
I'm also going to try to address searching for the option group.

**Comment by jachin** [comment]
There appears to also be an issue when adding custom options are enabled.
